server:
  port: 8089
# 配置日志打印级别
logging:
  level:
    root: INFO
# 配置静态文件引用目录
wyait:
  picpath: D:/images/
# spring相关配置
spring:
    mvc:
      static-path-pattern: /**
      #view:
      #  prefix: /
      # suffix: .jsp
    devtools:
        restart:
          exclude: templates/**
          additional-paths: src/main/
          enabled: false
    thymeleaf:
        suffix: .html
        cache: false
    datasource:
        name: test
        url: jdbc:mysql://10.110.1.117/rss?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&useUnicode=true
        username: root
        password: InspurYh@777
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 2
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        validationQuery: SELECT 1
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxOpenPreparedStatements: 20
    # redis配置，以下有默认配置的也可以使用默认配置
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 0
      #Spring Boot 2.0.0.M7中原有的redis配置方法过时，加了一层jedis
      jedis:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 0
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/public/,file:${wyait.picpath}
## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.*.data  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
